# Generated by Django 3.1.3 on 2020-12-03 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('title', models.CharField(max_length=255, verbose_name='Название викторины')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('views_number', models.IntegerField(default=0, verbose_name='кол просмотров')),
                ('start_at', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторины',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.quiz')),
            ],
            options={
                'verbose_name': 'Результат викторины',
                'verbose_name_plural': 'Результаты викторин',
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='Question_audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Порядковый номер')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('anwser1', models.CharField(max_length=100, verbose_name='Композитор')),
                ('answer2', models.CharField(max_length=100, verbose_name='Название')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('audiofile', models.FileField(upload_to='quiz_audio/')),
                ('quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Quiz_Questions', to='blog.quiz')),
                ('quizes', models.ManyToManyField(blank=True, related_name='Quiz_Questions_ManyToMany', to='blog.Quiz')),
            ],
            options={
                'verbose_name': 'Аудио вопрос',
                'verbose_name_plural': 'Аудио вопросы',
                'ordering': ['number', 'text'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=100, verbose_name='Ответ1')),
                ('answer2', models.CharField(blank=True, max_length=100, verbose_name='Ответ 2')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.question_audio', verbose_name='вопрос')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='AnswersList', to='blog.quiz_result')),
            ],
        ),
    ]
