# Generated by Django 3.1.3 on 2020-12-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201203_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes2', to='blog.question_audio', verbose_name='Вопрос 2'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes1', to='blog.question_audio', verbose_name='Вопрос 1'),
        ),
    ]
