# Generated by Django 3.1.3 on 2020-12-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201203_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question_audio',
            options={'ordering': ['id'], 'verbose_name': 'Аудио вопрос', 'verbose_name_plural': 'Аудио вопросы'},
        ),
        migrations.RenameField(
            model_name='question_audio',
            old_name='text',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
