# Generated by Django 3.1.3 on 2020-12-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201204_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questio10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes10', to='blog.question_audio', verbose_name='Вопрос 10'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes3', to='blog.question_audio', verbose_name='Вопрос 3'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes4', to='blog.question_audio', verbose_name='Вопрос 4'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes5', to='blog.question_audio', verbose_name='Вопрос 5'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes6', to='blog.question_audio', verbose_name='Вопрос 6'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes7', to='blog.question_audio', verbose_name='Вопрос 7'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes8', to='blog.question_audio', verbose_name='Вопрос 8'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quizes9', to='blog.question_audio', verbose_name='Вопрос 9'),
        ),
    ]
