# Generated by Django 3.1.3 on 2020-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201204_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['created_at'], 'verbose_name': 'Викторина', 'verbose_name_plural': 'Викторины'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_at',
            field=models.DateTimeField(verbose_name='Показывать после'),
        ),
    ]
